name: face_battle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.9+7

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  rive: ^0.12.3
  provider: ^6.1.1
  http: ^1.2.0
  logger: ^2.0.2
  shared_preferences: ^2.2.0
  video_player: ^2.8.2
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_analytics: ^11.0.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.3
  google_mobile_ads: ^5.0.0
  confetti: ^0.7.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  flutter_screenutil: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.6
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  in_app_purchase: ^3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/dice/
    - assets/icons/
    # - assets/config/
    # 统一的本地资源目录结构 npcs/[npcId]/[skinId]/
    - assets/npcs/0001/1/
    - assets/npcs/0002/1/
    # VIP NPC暂时使用云端资源
    # - assets/npcs/1001/1/
    # - assets/npcs/1002/1/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A0000"  # 深黑红色
  adaptive_icon_foreground: "assets/icons/app_logo.png"
  remove_alpha_ios: true
  ios_background_color: "#1A0000"  # iOS也使用深黑红色背景
