// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgB7JUYtcxBHfFNteTLzey_UjWEJTYvc',
    appId: '1:733677362915:web:12e394b3f7db746c7cafd6',
    messagingSenderId: '733677362915',
    projectId: 'liarsdice-fd930',
    authDomain: 'liarsdice-fd930.firebaseapp.com',
    storageBucket: 'liarsdice-fd930.firebasestorage.app',
    measurementId: 'G-6H3LPR8NBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIMvfLWOrdBtcB5CQpEmEoQISVyBY_-uk',
    appId: '1:733677362915:android:19ca66556c94abf17cafd6',
    messagingSenderId: '733677362915',
    projectId: 'liarsdice-fd930',
    storageBucket: 'liarsdice-fd930.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMxmbSFHlClnSoH7TMxvNKh6oHECaU1JM',
    appId: '1:733677362915:ios:83fe45433dc551df7cafd6',
    messagingSenderId: '733677362915',
    projectId: 'liarsdice-fd930',
    storageBucket: 'liarsdice-fd930.firebasestorage.app',
    iosClientId: '733677362915-q5oft68jvfk9dgnsamk5813vet4ipqjh.apps.googleusercontent.com',
    iosBundleId: 'com.odt.liarsdice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMxmbSFHlClnSoH7TMxvNKh6oHECaU1JM',
    appId: '1:733677362915:ios:83fe45433dc551df7cafd6',
    messagingSenderId: '733677362915',
    projectId: 'liarsdice-fd930',
    storageBucket: 'liarsdice-fd930.firebasestorage.app',
    iosClientId: '733677362915-q5oft68jvfk9dgnsamk5813vet4ipqjh.apps.googleusercontent.com',
    iosBundleId: 'com.odt.liarsdice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgB7JUYtcxBHfFNteTLzey_UjWEJTYvc',
    appId: '1:733677362915:web:c5291c2b64c174597cafd6',
    messagingSenderId: '733677362915',
    projectId: 'liarsdice-fd930',
    authDomain: 'liarsdice-fd930.firebaseapp.com',
    storageBucket: 'liarsdice-fd930.firebasestorage.app',
    measurementId: 'G-18SETVFWWR',
  );
}
